LOIS_BUNDLE_IDENTIFIER = 'loisBundle'
HYPOTHESIS_BUNDLE_IDENTIFIER = 'hypothesisBundle'
TRIGGER_BUNDLE_IDENTIFIER = 'triggerBundle'
QUESTION_BUNDLE_IDENTIFIER = 'questionBundle'
# hypothesisVariablesBinding
HYPOTHESIS_VARIABLES_BINDING = 'hypothesisVariablesBinding'
QUESTION_VARIABLES_BINDING = 'questionVariablesBinding'
META_WORKFLOW_VARIABLES_BINDING = 'metaWorkflowVariablesBinding'
META_WORKFLOW_INPUT_FILE_BINDING = 'metaWorkflowInputsFileBinding'

DISK_ONTOLOGY = "http://disk-project.org/ontology/disk#"
DISK_ONTOLOGY_CONFIDENCE_REPORT_LOCALNAME = "ConfidenceReport"
DISK_ONTOLOGY_CONFIDENCE_REPORT = DISK_ONTOLOGY + \
    DISK_ONTOLOGY_CONFIDENCE_REPORT_LOCALNAME
DISK_ONTOLOGY_HAS_CONFIDENCE_VALUE_LOCALNAME = "hasConfidenceValue"
DISK_ONTOLOGY_HAS_CONFIDENCE_VALUE = DISK_ONTOLOGY + \
    DISK_ONTOLOGY_HAS_CONFIDENCE_VALUE_LOCALNAME

DISK_ONTOLOGY_TRIGGER_LINE_OF_INQUIRY = "http://disk-project.org/ontology/disk#TriggeredLineOfInquiry"
PROV_GENERATED_AT_TIME = "http://www.w3.org/ns/prov#generatedAtTime"
PROV_GENERATED_AT_TIME_LOCALNAME = "generatedAtTime"
